### ISSUE TITLE
An Austrian Feiertag is missing

### ISSUE THREAD

**Issue by homecineplexx** [Pix---/ioBroker.feiertage#34]
The 8.12 (Mariä Empfängnis) is missing. 
Please can you update this?

Or is it possible to get a checkbox for pre-selecting.
German or Austria ?

**Comment by Pix---** [comment]
I have added Mariä Empfängnis / Feast of the Immaculate Conception to the Github-Version 1.0.11.
Please test this version and give feedback.
I need to update the npm version, which ist still 1.0.9 now.

It would be possible to preselect the checkboxes on the basis of the users homecountry or system language. But due to too many more different options as the are even different holidays within one country the user will have to select his personal holidays himself. That is far easier.
